version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

